export const SAVE_FORM_DATA = 'SAVE_FORM_DATA';
export const SAVE_CUSTOM_FIELD_DATA = 'SAVE_CUSTOM_FIELD_DATA';
export const STOP_APP_FLOW = 'STOP_APP_FLOW';
export const SAVE_CURRENT_FORM_FILLING = 'SAVE_CURRENT_FORM_FILLING';
